version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - MONGO_URI=${MONGO_URI}

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Vite runs on 5173 locally but we expose Nginx on 3000

